config/routes.rb
Rails.application.routes.draw do
  
  devise_for :providers, controllers: {
    registrations: 'providers/registrations',
    sessions: 'providers/sessions'
  }
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }, skip: :registrations
  resources :contacts
  root 'welcome#index'
  get '/terms', to: 'terms#index'
  devise_for :restaurants, controllers: { 
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions' 
  }

  resources :allergies
  
  get '/admin_dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'
  get '/admin_dashboard_restaurants', to: 'admin_dashboard#restaurants', as: 'admin_dashboard_restaurants'
  get '/admin_dashboard_contacts', to: 'admin_dashboard#contacts', as: 'admin_dashboard_contacts'
  resources :restaurants do 
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    get '/dashboard/orders', to: 'dashboard#orders', as: 'dashboard_orders', format: :js
    get '/dashboard/history', to: 'dashboard#history', as: 'dashboard_history'
    get '/dashboard/tables', to: 'dashboard#tables', as: 'dashboard_tables'
    get '/dashboard/menu', to: 'dashboard#menu', as: 'dashboard_menu'
    get '/dashboard/special_menus', to: 'dashboard#special_menus', as: 'dashboard_special_menus'
    get '/dashboard/payment_information', to: 'dashboard#payment_information', as: 'dashboard_payment_information'
    patch '/dashboard/update_payment_information', to: 'dashboard#update_payment_information', as: 'update_payment_information'
    post '/dashboard/authenticate', to: 'dashboard#authenticate', as: 'authenticate_dashboard'
    post '/dashboard/unauthenticate', to: 'dashboard#unauthenticate', as: 'unauthenticate_dashboard'  
    resources :categories
    resources :food_items
    resources :special_menus do 
      resources :food_types do 
        resources :food_items
      end
      resources :images
    end 
    resources :tables do
      member do
        get 'download_qr_code'
      end
    end
    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add_to_cart'
      delete 'remove_from_cart/:cart_item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
      delete 'remove_special_menu/:cart_item_id', to: 'carts#remove_special_menu', as: 'remove_special_menu'
      delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
    end
    resources :orders, only: [:new, :create, :destroy] do 
      collection do
        get 'thank_you/:pdf_path', action: :thank_you, as: 'thank_you'
      end
    end
  end
  resources :contacts, only: [:new, :create]
  get '/stripe_checkout', to: 'orders#stripe_checkout', as: 'stripe_checkout'
  get '/receipts/:pdf_path/:restaurant_id', to: 'receipts#download', as: 'download_receipt'
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    has_and_belongs_to_many :food_items, join_table: :food_item_allergies
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :set_restaurant
    before_action :authenticate_restaurant_if_no_admin
    before_action :check_restaurant_authorization
    before_action :check_password, only: [:index, :payment_information]

    def index
        @current_day_revenue = @restaurant.daily_revenues.where(day: Date.today.day, month: Date.today.month, year: Date.today.year).sum(:revenue)
        @current_month_revenue = @restaurant.monthly_revenues.where(month: Date.today.month, year: Date.today.year).sum(:revenue)
        @current_year_revenue = @restaurant.monthly_revenues.where(year: Date.today.year).sum(:revenue)


        @popular_food_items = FoodItem.joins(:cart_items)
        .where(food_items: { restaurant_id: @restaurant.id })
        .group('food_items.id')
        .order('SUM(cart_items.quantity) DESC')
        .limit(5)

        @popular_special_menus = SpecialMenu.joins(:cart_items)
                      .where(special_menus: { restaurant_id: @restaurant.id })
                      .group('special_menus.id')
                      .order('SUM(cart_items.quantity) DESC')
                      .limit(5)


        @revenues = @restaurant.daily_revenues.where(month: Date.today.month, year: Date.today.year)
                            .pluck(:date, :revenue)
    end

    def authenticate
        password = params[:password]
        if @restaurant.valid_password?(password)
          session[:authenticated] = true
        else
          session[:authenticated] = false
        end
        redirect_to request.referrer || restaurant_dashboard_path(@restaurant)
    end

    def unauthenticate
        password = params[:password]
        if @restaurant.valid_password?(password)
          session[:authenticated] = false
        end
        redirect_to request.referrer || restaurant_dashboard_path(@restaurant)
    end

    def orders
        @orders = @restaurant.orders.order(created_at: :desc)
    end

    def history
        @deleted_orders = @restaurant.deleted_orders.order(order_date: :desc)
    end

    def tables
    end

    def menu
    end 

    def special_menus
    end

    def payment_information
    end
    
    def update_payment_information        
        if @restaurant.valid_password?(params[:restaurant][:current_password])
          if @restaurant.update(payment_information_params)
            redirect_to restaurant_dashboard_payment_information_path(@restaurant), notice: 'Payment information updated successfully!'
          else
            render :payment_information
          end
        else
          @restaurant.errors.add(:current_password, 'is incorrect')
          render :payment_information
        end
    end

    private

    def set_restaurant 
      @restaurant = Restaurant.friendly.find(params[:restaurant_id])
    end

    def payment_information_params
        params.require(:restaurant).permit(:stripe_account_id, :bank_account_number, :bank_routing_number, :bank_account_holder_name)
    end

    def check_password
        unless session[:authenticated]
          @show_revenue = false
        end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/history.html.erb
<%= render 'layouts/header' %>

<section class="home">
  <div class="container dashboard-index" style="height: 100%">
  <h2 class="menu-name" style="margin-top:10px;">Historial</h2>
    <table class="table order-table">
      <thead>
        <tr>
          <th>Fecha y hora</th>
          <th>Pedido</th>
          <th>Tabla</th>
          <th>Total</th>
          <th>Forma de pago</th>
        </tr>
      </thead>
      <tbody>
        <% @deleted_orders.each do |order| %>
          <tr>
          <td><h6><%= order.created_at.strftime("%Y-%m-%d %H:%M") %></h6></td>
          <td>
          <% order.cart_items.each do |cart_item| %>              
            <% if cart_item.special_menu.present? %>
            <p class="order-food-item" style="display: inline;">
            <%= cart_item.quantity %>x
            <%= cart_item.special_menu.name %>: </p>
            <% cart_item.cart_item_food_items.each do |cart_item_food_item| %>
              <p class="order-food-item pedido-special-menu" style="display: inline;"> 
              <%= cart_item_food_item.food_item.name %>
            </p><% end %>
            <br>
            <% end %>
          <% end %>
          <% order.cart_items.each do |cart_item| %>              
            <% if cart_item.special_menu.present? %>
              <p class="order-food-item" style="display: inline;">
              <% cart_item.special_menu.food_types.where(have_to_select_one: nil).each do |food_type| %>
                <% food_type.food_items.each do |food_item| %>
                  <p class="order-food-item" style="display: inline;"><%= cart_item.quantity %>x
                  <%= food_item.name %><% if food_type.food_items.last != food_item %>, <% end %></p>  
                <% end %>
              <% end %>
            <br>
            <% elsif cart_item.cart_item_food_items.present? %>
              <% cart_item.cart_item_food_items.each do |cart_item_food_item| %>
                <p class="order-food-item" style="display: inline;">
                <%= cart_item.quantity %>x
                  <%= cart_item_food_item.food_item.name %><% if order.cart_items.where(special_menu_id: nil).last.cart_item_food_items.first != cart_item_food_item %>, <% end %></p>
              <% end %>
            <% end %>
          <% end %>
          </td>
          <td><h6><%= order.table_number %></h6></td>
          <td><h6 class=""><%= number_to_currency(order.total_price, precision: 2, unit: '€') %></h6></td>
          <td>
            <h6><%= order.payment_method %></h6>
          </td>
        </tr>
        
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/dashboard/index.html.erb
    <%= render 'layouts/header' %>

    <section class="home dashboard-index" style="height: 100%">
        <div class="container">
            <h1>Bienvenido a <%= @restaurant.name %></h1>
            <div class="row">
                <div class="col-md-4">
                    <div class="profit-box">
                        <% if session[:authenticated] %>
                            <h2>Ingresos del día</h2>
                            <h3><%= number_to_currency(@current_day_revenue) %></h3>
                        <% else %>
                            <h2>Ingresos del día</h2>
                            <h3>******</h3>
                        <% end %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="profit-box">
                    <% if session[:authenticated] %>
                        <h2>Ingresos del mes</h2>
                        <h3><%= number_to_currency(@current_month_revenue) %></h3>
                    <% else %>
                        <h2>Ingresos del mes</h2>
                        <h3>******</h3>
                    <% end %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="profit-box">
                    <% if session[:authenticated] %>
                        <h2>Ingresos del año</h2>
                        <h3><%= number_to_currency(@current_year_revenue) %></h3>
                    <% else %>
                        <h2>Ingresos del año</h2>
                        <h3>******</h3>
                    <% end %>
                    </div>
                </div>
            </div>    
            <% unless session[:authenticated] %>
            <div class="password-section">
                <h2>Ingrese la contraseña para ver los ingresos</h2>
                <%= form_with url: { action: 'authenticate', method: :post } do |form| %>
                    <div class="row">
                        <div class="col-md-3">
                            <%= form.password_field :password, placeholder: 'Contraseña', class: "form-control" %>
                        </div>
                        <div class="col-md-1">
                            <%= form.submit 'Ingresar', class: 'btn btn-primary' %>
                        </div>
                    </div>
                <% end %>
            </div>
            <% end %>
            <% if session[:authenticated] %>
            <div class="password-section">
                <h2>Ingrese la contraseña para ocultar los ingresos</h2>
                <%= form_with url: { action: 'unauthenticate', method: :post } do |form| %>
                    <div class="row">
                        <div class="col-md-3">
                            <%= form.password_field :password, placeholder: 'Contraseña', class: "form-control" %>
                        </div>
                        <div class="col-md-1">
                            <%= form.submit 'Ingresar', class: 'btn btn-primary' %>
                        </div>
                    </div>
                <% end %>
            </div>
            <% end %>





  </div>
</section>
    

app/views/dashboard/menu.html.erb
<%= render 'layouts/header' %>

<section class="home">
<div class="container dashboard-index" style="height: 100%">
<%= link_to 'Nueva categoría', new_restaurant_category_path(@restaurant), class: "btn btn-primary btn-dashboard2 btn-margin-bottom" %> 
<%= link_to 'Nueva comida', new_restaurant_food_item_path(@restaurant), class: "btn btn-primary btn-dashboard2 btn-margin-bottom" %> 
<% @restaurant.categories.where(deleted_at: nil).each_with_index do |category, index| %>
  <h4><%= category.name %>
  <%= link_to "Modificar", edit_restaurant_category_path(@restaurant, category), class: "btn btn-primary btn-margin-bottom btn-margin-top btn-dashboard" %>
          <%= link_to 'Eliminar', restaurant_category_path(@restaurant, category), method: :delete, class: 'btn btn-danger btn-margin-bottom btn-margin-top btn-dashboard' %>
          </h4>
      <% category.food_items.where(deleted_at: nil).each_slice(4) do |food_items_slice| %>
        <div class="row">
          <% food_items_slice.each do |food_item| %>
            <div class="col-3 col-sm-3 col-md-3">
              <div class="food-item-dashboard text-center" data-toggle="modal" data-target="#foodItemModal"
                   data-name="<%= food_item.name %>"
                   data-description="<%= food_item.description %>"
                   data-price="<%= number_to_currency(food_item.price, precision: 2, unit: '€') %>"
                   data-image-url="<%= url_for(food_item.image) if food_item.image.attached? %>">
                <%= image_tag food_item.image, class: "menu-image-dashboard menu-item" if food_item.image.attached? %>
                <h6><%= food_item.name %></h6>
                <h6><%= number_to_currency(food_item.price, precision: 2, unit: '€') %></h6>
                <%= link_to "Modificar", edit_restaurant_food_item_path(@restaurant, food_item), class: "btn btn-primary btn-margin-bottom btn-margin-top btn-dashboard" %>
                <%= link_to 'Eliminar', restaurant_food_item_path(@restaurant, food_item), method: :delete, class: 'btn btn-danger btn-margin-bottom btn-margin-top btn-dashboard' %>
                <% if food_item.minimum_persons.present? %>
                <div class="move-left">
                  <i class='bx bx-user btn-margin-top' style="font-size: 30px;"></i> <%= food_item.minimum_persons %>
                </div>
                <% end %>
                <div class="move-right" style="margin-right: 15px">
                <% food_item.allergies.each do |allergy| %>
                  <div class="allergy-circle-food" style="background-color: <%= allergy.color %>;"></div>
                <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
<% end %>      

      </div>
</section>


<div class="modal fade" id="foodItemModal" tabindex="-1" role="dialog" aria-labelledby="foodItemModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-food text-center">
      <div class="modal-body">
        <div class="container-fluid">
              <div id="foodItemImageContainer">
              </div>
              <div id="foodItemDetails">
              </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('.food-item-dashboard').click(function() {
      var name = $(this).data('name');
      var description = $(this).data('description');
      var imageUrl = $(this).data('image-url');
      
      var imageContent = '<img src="' + imageUrl + '" alt="' + name + '" class="food-item-popup-image">';
      var detailsContent = '<div class="food-item-name">' + name + '</div>';
      detailsContent += '<div class="food-item-description">' + description + '</div>';

      $('#foodItemImageContainer').html(imageContent);
      $('#foodItemDetails').html(detailsContent);
    });
  });
</script>
<style>


<style>


  .food-item-name {
    font-size: 20px;
    font-weight: bold;
    margin-top: 10px;
  }

  .food-item-description {
    font-size: 18px;
    margin-top: 10px;
  }
</style>

app/views/dashboard/orders.html.erb
<%= render 'layouts/header' %>

<section class="home">
  <div class="container dashboard-index" style="height: 100%">
  <h2 class="menu-name" style="margin-top:10px">Pedidos</h2>
    <table class="table order-table">
      <thead>
        <tr>
          <th>Fecha y hora</th>
          <th>Pedido</th>
          <th>Tabla</th>
          <th>Total</th>
          <th>Forma de pago</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="orders-container">
        <%= render partial: 'orders/order', collection: @orders %>
      </tbody>
    </table>
  </div>
</section>


<audio id="notification-sound" controls preload="auto">
  <source src="<%= asset_path('order.mp3') %>" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>

<script>
document.addEventListener("turbolinks:load", function() {
  var restaurantId = <%= @restaurant.id %>;
  const notificationSound = document.getElementById('notification-sound');
  let currentOrderCount = 0;

  function refreshOrdersContainer() {
    $.get('/restaurants/' + restaurantId + '/dashboard/orders', function(data) {
      const newOrderCount = $(data).find('.order-row').length; // Update this selector

      // Compare order counts to detect new orders
      if (newOrderCount > currentOrderCount) {
        // Play the notification sound for new orders
        notificationSound.play();
      }

      currentOrderCount = newOrderCount;

      // Update the orders-container
      $('#orders-container').html($(data).find('#orders-container').html());
    });
  }

  // Call the function to refresh the content after a certain interval
  setInterval(refreshOrdersContainer, 5000); // Refresh every 5 seconds
});

</script>


<style>
    #notification-sound {
      display: none; 
    }
</style>

app/views/dashboard/orders.js.erb
// app/views/restaurants/dashboard/orders.js.erb
$("#orders-container").html('<%= j render partial: "orders/order", collection: @orders %>');

app/views/dashboard/payment_information.html.erb
<%= render 'layouts/header' %>

<section class="home" style="height: 100%">
  <div class="container dashboard-index" style="margin-top: 10px">
  <h2>Información de cuenta bancaria</h2>
  <% if session[:authenticated] %>
    <%= form_for(@restaurant, url: restaurant_update_payment_information_path(@restaurant), html: { class: 'form-horizontal' }) do |form| %>
      <!-- Add form fields for payment information -->
      <div class="form-group">
        <%= form.label :stripe_account_id, "Stripe account ID", class: 'control-label col-sm-4' %>
        <div class="col-sm-5">
          <%= form.text_field :stripe_account_id, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
          <%= form.label :current_password, "Contraseña actual" %>
          <div class="col-sm-5">
            <%= form.password_field :current_password, autocomplete: "current-password", class: 'form-control' %>
          </div>
      </div>
    
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= form.submit 'Actualizar', class: 'btn btn-primary btn-margin-top' %>
        </div>
      </div>
    <% end %>
    <div class="password-section">
    <div class="col-sm-5">
    <h3>Ingrese la contraseña para ocultar la informacion del cuenta bancaria</h3>
  </div> 
      <%= form_with url: { action: 'unauthenticate', method: :post } do |form| %>
        <div class="row">
            <div class="col-md-3">
                <%= form.password_field :password, placeholder: 'Contraseña', class: "form-control" %>
            </div>
            <div class="col-md-1">
                <%= form.submit 'Ingresar', class: 'btn btn-primary' %>
            </div>
        </div>
    <% end %>
    </div>
    <% else %>
    <%= form_for(@restaurant, url: restaurant_update_payment_information_path(@restaurant), html: { class: 'form-horizontal' }) do |form| %>
      <!-- Add form fields for payment information -->
      <div class="form-group">
        <%= form.label :stripe_account_id, "Stripe account ID", class: 'control-label col-sm-4' %>
        <div class="col-sm-4">
          <%= form.text_field :stripe_account_id, value: '*********************', class: 'form-control', readonly: true %>
        </div>
      </div>
    <% end %>
    <div class="password-section">
    <div class="col-sm-6">
      <h3>Ingrese la contraseña para ver la informacion del cuenta bancaria</h3>
    </div>            
        <%= form_with url: { action: 'authenticate', method: :post } do |form| %>
                    <div class="row">
                        <div class="col-md-3">
                            <%= form.password_field :password, placeholder: 'Contraseña', class: "form-control" %>
                        </div>
                        <div class="col-md-1">
                            <%= form.submit 'Ingresar', class: 'btn btn-primary' %>
                        </div>
                    </div>
                <% end %>
            </div>
    <% end %>
  </div>
</section>

app/views/dashboard/special_menus.html.erb
<%= render 'layouts/header' %>

<section class="home">
<div class="container dashboard-index" style="height: 100%">
<h2 style="margin-top:10px">Menús especiales</h2>
<%= link_to "Nuevo menu", new_restaurant_special_menu_path(@restaurant), class: "btn btn-primary btn-dashboard2", style: "margin-bottom: 20px;" %>
<div class="row">
<% @restaurant.special_menus.where(deleted_at: nil).order(created_at: :desc).each_slice(2) do |special_menus_group| %>
  <div class="row">
    <% special_menus_group.each do |special_menu| %>
        <div class="col-md-6">
          <div class="special-menu-container container">
            <%= form_with(url: "#", method: :post, local:true, class: 'special-menu-form') do |form| %>
              <%= form.hidden_field :special_menu_id, value: special_menu.id %>
              <div class="row">
                <div class="col-5 col-sm-5 col-md-5">
                <div id="carousel<%= special_menu.id %>" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    <% special_menu.images.each_with_index do |image, index| %>
                      <div class="carousel-item <%= 'active' if index == 0 %>">
                        <%= image_tag image.image, class: "d-block w-100 special-menu-dashboard-image" %>
                      </div>
                    <% end %>
                  </div>
                  <a class="carousel-control-prev" href="#carousel<%= special_menu.id %>" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carousel<%= special_menu.id %>" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </a>
                </div>
                <%= link_to "Añadir Imagen", new_restaurant_special_menu_image_path(@restaurant, special_menu), class: "btn btn-primary btn-margin-bottom btn-margin-top btn-dashboard" %>
                </div>
                <div class="col-7 col-sm-7 col-md-7">
                  <% special_menu.food_types.order(created_at: :asc).each do |food_type| %>
                    <div class="form-group">
                      <%= form.label "food_item_ids[#{food_type.id}]", food_type.name, style: "font-size: 20px" %>
                      <% if !food_type.have_to_select_one %>
                        <p>
                          <%= simple_format(food_type.description, style: "font-size: 18px;") %>
                        </p>
                      <% end %>
                      <% if food_type.have_to_select_one == true %>
                        <%= form.collection_select "food_item_ids[#{food_type.id}]", food_type.food_items, :id, :name, { prompt: true, selected: food_type.food_items.first.id }, class: 'form-control' %>
                      <% end %>
                    </div>
                    <%= link_to "Modificar", edit_restaurant_special_menu_food_type_path(@restaurant, special_menu, food_type), class: "btn btn-primary btn-margin-bottom btn-margin-top btn-dashboard" %>
                    <%= link_to 'Eliminar', restaurant_special_menu_food_type_path(@restaurant, special_menu, food_type), method: :delete, class: 'btn btn-danger btn-margin-bottom btn-margin-top btn-dashboard' %>
                  <% end %><br>
                  <%= link_to "Añadir categoría", new_restaurant_special_menu_food_type_path(@restaurant, special_menu), class: "btn btn-primary btn-dashboard btn-margin-top" %>
                </div>
              </div>
              <div class="text-center">
                  <h4 class="special-menu-name"><%= special_menu.name %></h4>
                  <h6 class="menu-price"><%= number_to_currency(special_menu.price, precision: 2, unit: '€') %></h6>
                  <i class='bx bx-user' style="font-size: 30px;"></i> <%= special_menu.minimum_persons %>
                  <% end %>
              </div>
              <%= link_to "Modificar", edit_restaurant_special_menu_path(@restaurant, special_menu), class: "btn btn-primary btn-margin-bottom btn-dashboard" %>
              <%= link_to 'Eliminar', restaurant_special_menu_path(@restaurant, special_menu), method: :delete, class: 'btn btn-danger btn-margin-bottom btn-dashboard' %>
              <i class='bx bx-info-circle btn-margin-top menu-item-info move-right' style="font-size: 40px;" data-toggle="modal" data-target="#menuItemModal"
                data-name="<%= special_menu.name %>"
                data-description="<%= special_menu.description %>"
                data-instructions="<%= special_menu.instructions %>"
                data-minimum-persons="<%= special_menu.minimum_persons %>"
              ></i>
              
          </div>
        </div>
      
    <% end %>
  </div>
<% end %>

</div>
</div>
</section>



<div class="modal fade" id="menuItemModal" tabindex="-1" role="dialog" aria-labelledby="menuItemModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-food">
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12 col-sm-12 col-md-12">
              <div id="menuItemDetails">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

$(document).ready(function() {
  $('.menu-item-info').click(function() {
    var name = $(this).data('name');
    var description = $(this).data('description');
    var instructions = $(this).data('instructions');
    var minimumpersons = $(this).data('minimum-persons');
    
    var detailsContent = '<div class="menu-item-name">' + name + '</div>';
    detailsContent += '<div class="menu-item-description">' + description + '</div>';
    detailsContent += '<div class="menu-item-instructions">' + instructions + '</div>';
    detailsContent += '<div class="menu-item-minimum-persons">' + '<i class="bx bx-user" style="font-size: 30px;"></i> ' + minimumpersons + " personas mínimas" + '</div>';
    $('#menuItemDetails').html(detailsContent);
  });
});

</script>

app/views/dashboard/tables.html.erb
<%= render 'layouts/header' %>

<section class="home" style="height: 100%">
<div class="container dashboard-index" style="margin-top: 10px">
<h2>Tablas</h2>
<div style="margin-top: 10px">
    <%= link_to 'Nueva tabla', new_restaurant_table_path(@restaurant), class: "btn btn-primary btn-dashboard" %>
</div>
<div class="row" style="margin-top: 20px"> 
    <% @restaurant.tables.each do |table| %>
        <div class="col-3 col-sm-6 col-md-3" style="margin-top: 20px">
            <h5>Tabla <%= table.table_number %></h5>
            <%= image_tag(url_for(table.qrcode), class: "qr-code") %><br>
            <%= link_to 'Descargar', download_qr_code_restaurant_table_path(@restaurant, table, format: :png), target: '_blank', class: "btn btn-primary btn-dashboard" %>
            <%= link_to "Modificar", edit_restaurant_table_path(@restaurant, table), class: "btn btn-primary btn-margin-bottom btn-margin-top btn-dashboard" %>
            <%= link_to 'Eliminar', restaurant_table_path(@restaurant, table), method: :delete, class: 'btn btn-danger btn-margin-bottom btn-margin-top btn-dashboard' %>
        </div>
    <% end %>
</div>
</div>
</section>