config/routes.rb
Rails.application.routes.draw do
  
  devise_for :providers, controllers: {
    registrations: 'providers/registrations',
    sessions: 'providers/sessions'
  }
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }, skip: :registrations
  resources :contacts
  root 'welcome#index'
  get '/terms', to: 'terms#index'
  devise_for :restaurants, controllers: { 
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions' 
  }

  resources :allergies
  
  get '/admin_dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'
  get '/admin_dashboard_restaurants', to: 'admin_dashboard#restaurants', as: 'admin_dashboard_restaurants'
  get '/admin_dashboard_contacts', to: 'admin_dashboard#contacts', as: 'admin_dashboard_contacts'
  resources :restaurants do 
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    get '/dashboard/orders', to: 'dashboard#orders', as: 'dashboard_orders', format: :js
    get '/dashboard/history', to: 'dashboard#history', as: 'dashboard_history'
    get '/dashboard/tables', to: 'dashboard#tables', as: 'dashboard_tables'
    get '/dashboard/menu', to: 'dashboard#menu', as: 'dashboard_menu'
    get '/dashboard/special_menus', to: 'dashboard#special_menus', as: 'dashboard_special_menus'
    get '/dashboard/payment_information', to: 'dashboard#payment_information', as: 'dashboard_payment_information'
    patch '/dashboard/update_payment_information', to: 'dashboard#update_payment_information', as: 'update_payment_information'
    post '/dashboard/authenticate', to: 'dashboard#authenticate', as: 'authenticate_dashboard'
    post '/dashboard/unauthenticate', to: 'dashboard#unauthenticate', as: 'unauthenticate_dashboard'  
    resources :categories
    resources :food_items
    resources :special_menus do 
      resources :food_types do 
        resources :food_items
      end
      resources :images
    end 
    resources :tables do
      member do
        get 'download_qr_code'
      end
    end
    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add_to_cart'
      delete 'remove_from_cart/:cart_item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
      delete 'remove_special_menu/:cart_item_id', to: 'carts#remove_special_menu', as: 'remove_special_menu'
      delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
    end
    resources :orders, only: [:new, :create, :destroy] do 
      collection do
        get 'thank_you/:pdf_path', action: :thank_you, as: 'thank_you'
      end
    end
  end
  resources :contacts, only: [:new, :create]
  get '/stripe_checkout', to: 'orders#stripe_checkout', as: 'stripe_checkout'
  get '/receipts/:pdf_path/:restaurant_id', to: 'receipts#download', as: 'download_receipt'
end

app/models/special_menu.rb
class SpecialMenu < ApplicationRecord
  belongs_to :restaurant
  has_many :food_types, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :order_special_menus, dependent: :destroy
  has_many :orders, through: :order_special_menus
  has_many :deleted_order_special_menus, dependent: :destroy
  has_many :deleted_orders, through: :deleted_order_special_menus
  
  has_many :images, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true
  validates :start_hour, presence: true
  validates :end_hour, presence: true
  validates :minimum_persons, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def in_time_range?
    current_hour = Time.now.hour
    start_hour_hour = start_hour.hour
    end_hour_hour = end_hour.hour
    current_hour >= start_hour_hour && current_hour <= end_hour_hour
  end

  def soft_delete
    update(deleted_at: Time.now)
  end

  def active?
    deleted_at.nil?
  end
end

app/controllers/special_menus_controller.rb
class SpecialMenusController < ApplicationController
  before_action :set_restaurant
  before_action :authenticate_restaurant_if_no_admin
  before_action :check_restaurant_authorization
  before_action :set_special_menu, only: %i[ show edit update destroy ]

  def new
    @special_menu = @restaurant.special_menus.build
  end

  def edit
  end

  def create
    @special_menu = @restaurant.special_menus.build(special_menu_params)

    respond_to do |format|
      if @special_menu.save
        format.html { redirect_to restaurant_dashboard_special_menus_path(@restaurant), notice: "Special menu was successfully created." }
        format.json { render :show, status: :created, location: @special_menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @special_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @special_menu.update(special_menu_params)
        format.html { redirect_to restaurant_dashboard_special_menus_path(@restaurant), notice: "Special menu was successfully updated." }
        format.json { render :show, status: :ok, location: @special_menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @special_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @special_menu.soft_delete

    respond_to do |format|
      format.html { redirect_to restaurant_dashboard_special_menus_path(@restaurant), notice: "Special menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special_menu
      @special_menu = SpecialMenu.find(params[:id])
    end

    def set_restaurant 
      @restaurant = Restaurant.friendly.find(params[:restaurant_id])
    end

    # Only allow a list of trusted parameters through.
    def special_menu_params
      params.require(:special_menu).permit(:name, :restaurant_id, :description, :price, :instructions, :minimum_persons, :start_hour, :end_hour, food_item_ids: [])
    end
end

app/helpers/special_menus_helper.rb
module SpecialMenusHelper
end

app/views/special_menus/_form.html.erb
<%= form_for([@restaurant, @special_menu], html: { class: 'form-horizontal' }) do |form| %>
  <% if @special_menu.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@special_menu.errors.count, "error") %> prohibited this special_menu from being saved:</h2>
      <ul>
        <% @special_menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre", class: 'control-label col-sm-2' %>
    <div class="col-sm-4">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, "Descripción", class: 'control-label col-sm-2' %>
    <div class="col-sm-4">
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :price, "Precio", class: 'control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= form.text_field :price, step: '0.01', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :instructions, "Información adicional", class: 'control-label col-sm-2' %>
    <div class="col-sm-4">
      <%= form.text_area :instructions, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :minimum_persons , "Mínimo de personas", class: 'control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= form.number_field :minimum_persons, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :start_hour, "Hora de inicio", class: 'control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= form.time_field :start_hour, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :end_hour, "Hora final", class: 'control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= form.time_field :end_hour, class: "form-control" %>
    </div>
  </div>
  
  <% if @special_menu.images.present? %>
  <div class="form-group">
    <%= form.label "Imagenes", class: 'control-label col-sm-2' %>
      <% @special_menu.images.each_slice(4) do |images| %>
        <div class="row">
          <% images.each do |image| %>
            <div class="col-md-2">
              <%= image_tag image.image, class: "d-block w-100 special-menu-image-edit" %>
              <%= link_to 'Eliminar', restaurant_special_menu_image_path(@restaurant, @special_menu, image), method: :delete, class: 'btn btn-danger btn-margin-bottom btn-margin-top btn-dashboard' %>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= form.submit "Guardar", class: "btn btn-primary btn-margin-top" %>  
    </div>
  </div>
<% end %>

app/views/special_menus/edit.html.erb
<%= render 'layouts/header' %>

<section class="home" style="height: 100%; padding-top: 80px">
  <div class="container">
  <%= link_to restaurant_dashboard_special_menus_path(@restaurant), class: 'btn btn-primary btn-margin-bottom' do %>
    <%= content_tag :i, '', class: 'bx bx-arrow-back' %>
  <% end %>
    <h1>Modificar Menu</h1>
    <%= render 'form', special_menu: @special_menu %>
  </div>
</section>




    

app/views/special_menus/index.html.erb
<div class="container margin-top-container">
  <div class="col-md-7">
  <%= link_to 'Volver a ver la carta', @restaurant, class: "btn btn-primary" %>
    <h2 class="menu-name" style="margin-top:10px">Nuestros Menús</h2>
    <% @restaurant.special_menus.each do |special_menu| %>
      <!-- <%= link_to 'nuevo tipo', new_restaurant_special_menu_food_type_path(@restaurant, special_menu), class: "btn btn-primary" %> -->
      <div class="special-menu-container container">
        <%= form_tag '', method: :post do %>
        <h4 class="special-menu-name"><%= special_menu.name %></h4>
        <div class="row">
        <div class="col-4 col-sm-4 col-md-4">
        <%= image_tag special_menu.image, class: "menu-image menu-item" if special_menu.image.attached? %>
        </div>
        <div class="col-6 col-sm-6 col-md-6">
        <p><%= simple_format(special_menu.description) %></p>
        <% special_menu.food_types.each do |food_type| %>
          <div class="form-group">
            <label for="food_item_name"><h5><%= food_type.name %></h5></label>
            <% if food_type.have_to_select_one == true %>
              <%= select_tag 'food_item_name', options_for_select(food_type.food_items.map { |food_item| [food_item.name, food_item.name] }), class: 'form-control' %>
            <% else %>
              <% food_type.food_items.each do |food_item| %>
                <p><%= food_item.name %></p>
              <% end %> 
            <% end %>
          </div>
        <% end %>
        </div>
        <div class="col-2 col-sm-2 col-md-2">
          <h6><%= number_to_currency(special_menu.price, precision: 2, unit: '€') %></h6> 
          <%= link_to 'Add to Cart', add_to_cart_restaurant_cart_path(@restaurant, special_menu_id: special_menu.id), method: :post %>
        </div>
        <p style="margin-top:10px"><%= simple_format(special_menu.instructions) %></p>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
  <div class "col-me-3">
    <%= render 'shared/cart' %>
  </div>
</div>

app/views/special_menus/new.html.erb
<%= render 'layouts/header' %>

<section class="home" style="height: 100%; padding-top: 80px">
<div class="container">
<%= link_to restaurant_dashboard_special_menus_path(@restaurant), class: 'btn btn-primary btn-margin-bottom' do %>
  <%= content_tag :i, '', class: 'bx bx-arrow-back' %>
<% end %>
<h1>Nuevo menu</h1>

<%= render 'form', special_menu: @special_menu %>
</div>
</section>

app/views/special_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @special_menu.name %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @special_menu.restaurant %>
</p>

<%= link_to 'Edit', edit_special_menu_path(@special_menu) %> |
<%= link_to 'Back', special_menus_path %>