config/routes.rb
Rails.application.routes.draw do
  
  devise_for :providers, controllers: {
    registrations: 'providers/registrations',
    sessions: 'providers/sessions'
  }
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }, skip: :registrations
  resources :contacts
  root 'welcome#index'
  get '/terms', to: 'terms#index'
  devise_for :restaurants, controllers: { 
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions' 
  }

  resources :allergies
  
  get '/admin_dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'
  get '/admin_dashboard_restaurants', to: 'admin_dashboard#restaurants', as: 'admin_dashboard_restaurants'
  get '/admin_dashboard_contacts', to: 'admin_dashboard#contacts', as: 'admin_dashboard_contacts'
  resources :restaurants do 
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    get '/dashboard/orders', to: 'dashboard#orders', as: 'dashboard_orders', format: :js
    get '/dashboard/history', to: 'dashboard#history', as: 'dashboard_history'
    get '/dashboard/tables', to: 'dashboard#tables', as: 'dashboard_tables'
    get '/dashboard/menu', to: 'dashboard#menu', as: 'dashboard_menu'
    get '/dashboard/special_menus', to: 'dashboard#special_menus', as: 'dashboard_special_menus'
    get '/dashboard/payment_information', to: 'dashboard#payment_information', as: 'dashboard_payment_information'
    patch '/dashboard/update_payment_information', to: 'dashboard#update_payment_information', as: 'update_payment_information'
    post '/dashboard/authenticate', to: 'dashboard#authenticate', as: 'authenticate_dashboard'
    post '/dashboard/unauthenticate', to: 'dashboard#unauthenticate', as: 'unauthenticate_dashboard'  
    resources :categories
    resources :food_items
    resources :special_menus do 
      resources :food_types do 
        resources :food_items
      end
      resources :images
    end 
    resources :tables do
      member do
        get 'download_qr_code'
      end
    end
    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add_to_cart'
      delete 'remove_from_cart/:cart_item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
      delete 'remove_special_menu/:cart_item_id', to: 'carts#remove_special_menu', as: 'remove_special_menu'
      delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
    end
    resources :orders, only: [:new, :create, :destroy] do 
      collection do
        get 'thank_you/:pdf_path', action: :thank_you, as: 'thank_you'
      end
    end
  end
  resources :contacts, only: [:new, :create]
  get '/stripe_checkout', to: 'orders#stripe_checkout', as: 'stripe_checkout'
  get '/receipts/:pdf_path/:restaurant_id', to: 'receipts#download', as: 'download_receipt'
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    has_and_belongs_to_many :food_items, join_table: :food_item_allergies
end

app/views/shared/_cart.html.erb
<div class="modal fade" id="cartModal" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-edit" role="document">
    <div class="modal-content">
      <%= link_to restaurant_path(@restaurant, table_number: params[:table_number]), class: 'btn-transparent', style: "margin-right: 20px; position: relative; top: 5px" do %>
        <%= image_tag 'left.png', alt: 'CARTA', class: "back-btn" %>
      <% end %>
        <h5 class="modal-title" id="cartModalLabel"></h5>
      <div class="modal-body">

        <% if current_cart.present? %>
        <div id="cart-items">
          <% current_cart.cart_items.each do |cart_item| %>              
            <% if cart_item.special_menu.present? %>
              <div class="row cart-item" data-menu-id="<%= cart_item.id %>">
              <div class="col-6 col-sm-6 col-md-6">
                  <h5><%= cart_item.special_menu.name %></h5>
                  <p class="special-menu-cart-item-food-items" style="font-weight: bold; font-size: 10px; color:rgb(128, 0, 255);">
                  <% cart_item.cart_item_food_items.each do |cart_item_food_item| %>
                    <%= cart_item_food_item.food_item.name %><% if cart_item.cart_item_food_items.last.food_item != cart_item_food_item.food_item %>, <% end %>
                  <% end %>
                  </p>
              </div>
              <div class="col-2 col-sm-2 col-md-2 cart-buttons-wrapper">
                <h5 class="cart-item-quantity quantity">x <%= cart_item.quantity %></h5>
              </div>
              <div class="col-2 col-sm-2 col-md-2 cart-buttons-wrapper">
              <%= link_to '-', remove_special_menu_restaurant_cart_path(@restaurant, cart_item_id: cart_item.id), method: :delete, class: "btn btn-danger remove_special_menu", remote: true %>
              <%= form_with(url: add_to_cart_restaurant_cart_path(@restaurant, special_menu_id: cart_item.special_menu_id, food_item_ids: cart_item.cart_item_food_items.map { |item| [item.food_item_id, item.food_item_id.to_s] }.to_h ), method: :post, local:true, class: 'special-menu-form') do |form| %>
              <%= form.submit '+', class: "btn btn-primary" %>
              <% end %>
              </div>
                <div class="col-2 col-sm-2 col-md-2">
                  <h5 class="price"><%= number_to_currency(cart_item.special_menu.price * cart_item.quantity, precision: 2, unit: '€') %></h5>            
                </div>
                </div>  
            <% elsif cart_item.cart_item_food_items.present? %>
            <% cart_item.cart_item_food_items.each do |cart_item_food_item| %>
            <div class="row cart-item" data-food-id="<%= cart_item.id %>">
            <div class="col-6 col-sm-6 col-md-6">
                <h5><%= cart_item_food_item.food_item.name %></h5>
            </div>
            <div class="col-2 col-sm-2 col-md-2">
              <h5 class="cart-item-quantity quantity">x <%= cart_item.quantity %></h5>
            </div>
            <div class="col-2 col-sm-2 col-md-2 cart-buttons-wrapper">
            <%= link_to remove_from_cart_restaurant_cart_path(@restaurant, cart_item_id: cart_item.id), method: :delete, class: "btn-transparent remove-cart-item", remote: true do %>
              <%= image_tag 'minus.png', alt: 'Remove from Cart', class: "cart-add-btn" %>
            <% end %>
                        <%= form_with url: add_to_cart_restaurant_cart_path(@restaurant, food_item_id: cart_item_food_item.food_item_id), class: "add-to-cart", method: :post, local: true do |form| %>
              <%= form.button class: "btn-transparent" do %>
                <%= image_tag 'add.png', alt: 'Add to Cart', class: "cart-add-btn" %>
              <% end %>
            <% end %>
            
            </div>
            <div class="col-2 col-sm-2 col-md-2">
              <h5 class="price"><%= number_to_currency(cart_item_food_item.food_item.price * cart_item.quantity, precision: 2, unit: '€') %></h5>
            </div>
            </div>
            <% end %>
            <% end %>
          <% end %>
        </div>
        <h5 class="cart-total-price">Total: <%= number_to_currency(current_cart.total_price, precision: 2, unit: '€') %></h5>
        <%= link_to 'Pedir', '#', class: 'btn btn-primary', style:"margin-top: 20px; width: 100%; font-size: 35px !important; padding: 10px", 'data-toggle' => 'modal', 'data-target' => '#paymentMethodModal' %>
        <% else %>
          <p>Your cart is empty.</p>
        <% end %>
      </div>

    </div>
  </div>
</div>