config/routes.rb
Rails.application.routes.draw do
  
  devise_for :providers, controllers: {
    registrations: 'providers/registrations',
    sessions: 'providers/sessions'
  }
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }, skip: :registrations
  resources :contacts
  root 'welcome#index'
  get '/terms', to: 'terms#index'
  devise_for :restaurants, controllers: { 
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions' 
  }

  resources :allergies
  
  get '/admin_dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'
  get '/admin_dashboard_restaurants', to: 'admin_dashboard#restaurants', as: 'admin_dashboard_restaurants'
  get '/admin_dashboard_contacts', to: 'admin_dashboard#contacts', as: 'admin_dashboard_contacts'
  resources :restaurants do 
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    get '/dashboard/orders', to: 'dashboard#orders', as: 'dashboard_orders', format: :js
    get '/dashboard/history', to: 'dashboard#history', as: 'dashboard_history'
    get '/dashboard/tables', to: 'dashboard#tables', as: 'dashboard_tables'
    get '/dashboard/menu', to: 'dashboard#menu', as: 'dashboard_menu'
    get '/dashboard/special_menus', to: 'dashboard#special_menus', as: 'dashboard_special_menus'
    get '/dashboard/payment_information', to: 'dashboard#payment_information', as: 'dashboard_payment_information'
    patch '/dashboard/update_payment_information', to: 'dashboard#update_payment_information', as: 'update_payment_information'
    post '/dashboard/authenticate', to: 'dashboard#authenticate', as: 'authenticate_dashboard'
    post '/dashboard/unauthenticate', to: 'dashboard#unauthenticate', as: 'unauthenticate_dashboard'  
    resources :categories
    resources :food_items
    resources :special_menus do 
      resources :food_types do 
        resources :food_items
      end
      resources :images
    end 
    resources :tables do
      member do
        get 'download_qr_code'
      end
    end
    resource :cart, only: [:show] do
      post 'add_to_cart', to: 'carts#add_to_cart'
      delete 'remove_from_cart/:cart_item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
      delete 'remove_special_menu/:cart_item_id', to: 'carts#remove_special_menu', as: 'remove_special_menu'
      delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
    end
    resources :orders, only: [:new, :create, :destroy] do 
      collection do
        get 'thank_you/:pdf_path', action: :thank_you, as: 'thank_you'
      end
    end
  end
  resources :contacts, only: [:new, :create]
  get '/stripe_checkout', to: 'orders#stripe_checkout', as: 'stripe_checkout'
  get '/receipts/:pdf_path/:restaurant_id', to: 'receipts#download', as: 'download_receipt'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @contact = Contact.new
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= render 'layouts/header_welcome' %>

<section class="jumbotron jumbotron-bg bg-overlay text-center">
    <h1 class="display-4">La forma de pago más rápida</h1>
    <p class="lead">tus clientes pueden ver el menú y pagar la cuenta en 10 segundos</p>
    <%= link_to 'solicita una demo', new_contact_path, class: 'btn btn-primary btn-lg' %>
  </section>

  <div class="container" style="margin-top: 20px; margin-bottom: 90px;">
    <div class="row">
      <div class="col-md-4 col-xs-12 col-sm-12">
        <%= image_tag ("qr-code.png"), class: "scan-image" %>
        <h5>1. Escanear el código QR</h5>
      </div>
      <div class="col-md-4 col-xs-12 col-sm-12">
        <%= image_tag ("list.png"), class: "scan-image" %>
        <h5>2. Ver el menú y hacer el pedido</h5>
      </div>
      <div class="col-md-4 col-xs-12 col-sm-12">
        <%= image_tag ("atm-card.png"), class: "scan-image" %>
        <h5>3. Eligir un método de pago y pagar</h5>
      </div>
    </div>
  </div>


  <div class="faq_area section_padding_130" id="faq">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-12 col-sm-8 col-lg-6">
              <!-- Section Heading-->
              <div class="section_heading text-center wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                  <h3>Preguntas más frecuentes</h3>
                  <p>FAQs</p>
                  <div class="line"></div>
              </div>
          </div>
      </div>
      <div class="row justify-content-center">
          <div class="col-12 col-sm-10 col-lg-8">
              <div class="accordion faq-accordian" id="faqAccordion">
                  <div class="card border-0 wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
                      <div class="card-header" id="headingOne">
                          <h6 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">¿Por qué códigos QR?<span class="lni-chevron-up"></span></h6>
                      </div>
                      <div class="collapse" id="collapseOne" aria-labelledby="headingOne" data-parent="#faqAccordion">
                          <div class="card-body">
                              <p>Los códigos QR transforman la espera de la factura en algo que toma segundos. Sus clientes no solo pueden ver el menú, sino que también pueden pagar su cuenta, en tan solo 10 segundos. Los restaurantes ahora pueden concentrarse en lo esencial: cocinar comida increíble y ofrecer una excelente experiencia al cliente.</p>
                          </div>
                      </div>
                  </div>
                  <div class="card border-0 wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
                      <div class="card-header" id="headingTwo">
                          <h6 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">¿Bamboo es una aplicación?<span class="lni-chevron-up"></span></h6>
                      </div>
                      <div class="collapse" id="collapseTwo" aria-labelledby="headingTwo" data-parent="#faqAccordion">
                          <div class="card-body">
                              <p>Bamboo no es una aplicación, por lo que no la encontrarán en App Store o Play Store. en el momento en que los clientes escanean el código QR, son redirigidos a una aplicación web que les da acceso a su menú y les permite pagar al final de su comida. Sin registros, sin descargas.</p>
                          </div>
                      </div>
                  </div>
                  <div class="card border-0 wow fadeInUp" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
                      <div class="card-header" id="headingThree">
                          <h6 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">¿Bamboo funciona en todos los teléfonos móviles?<span class="lni-chevron-up"></span></h6>
                      </div>
                      <div class="collapse" id="collapseThree" aria-labelledby="headingThree" data-parent="#faqAccordion">
                          <div class="card-body">
                              <p>Sí, Bamboo funciona en todos los modelos y marcas de teléfonos inteligentes.</p>
                          </div>
                      </div>
                  </div>
                  <div class="card border-0 wow fadeInUp" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
                      <div class="card-header" id="headingFour">
                          <h6 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">¿Es fácil configurar Bamboo?<span class="lni-chevron-up"></span></h6>
                      </div>
                      <div class="collapse" id="collapseFour" aria-labelledby="headingFour" data-parent="#faqAccordion">
                          <div class="card-body">
                              <p>Si, una vez que registre su cuenta, nos envíe su plan de mesa y nosotros nos encargaremos del resto, incluida la producción de sus códigos QR.</p>
                          </div>
                      </div>
                  </div>
                  <div class="card border-0 wow fadeInUp" data-wow-delay="0.4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
                      <div class="card-header" id="headingFive">
                          <h6 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">¿Puedo subir un menú?<span class="lni-chevron-up"></span></h6>
                      </div>
                      <div class="collapse" id="collapseFive" aria-labelledby="headingFive" data-parent="#faqAccordion">
                          <div class="card-body">
                              <p>Sí, puedes subir tus propios menús. cuántos tienes y con qué frecuencia los actualizas es tu decisión.</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<div class="container text-center" style="margin-top: 90px;">
    <h2>¿Porque los pagos con código QR?</h2>
    <div class="row">
      <div class="col-md-3">
        <%= image_tag ("stopwatch.png"), class: "scan-image" %>
        <h5 style="margin-top: 10px">Reducen el tiempo de espera</h5>
      </div>
      <div class="col-md-3">
        <%= image_tag ("audience.png"), class: "scan-image" %>
        <h5 style="margin-top: 10px">Apoyan a los camareros</h5>
      </div>
      <div class="col-md-3">
        <%= image_tag ("interactive-content.png"), class: "scan-image" %>
        <h5 style="margin-top: 10px">Aumentan la digitalización del negocio</h5>
      </div>
      <div class="col-md-3">
        <%= image_tag ("revenue.png"), class: "scan-image" %>
        <h5 style="margin-top: 10px">Aumentan los ingresos</h5>
      </div>
    </div>
  </div>



<div class="container demo-form" style="margin-top: 100px;">
      <h2 class="text-center">Contacto</h2>

  <div class="row justify-content-center">
          <div class="col-md-7 d-flex align-items-stretch">
            <div class="contact-wrap w-100 p-md-5 p-4">
                <%= form_with(model: @contact, url: contacts_path, local: true,  class: "contact-form") do |form| %>
                  <div class="row">
                    <% if @contact.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

                        <ul>
                        <% @contact.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="col-md-6">
                      <div class="form-group" style="margin-bottom: 10px">
                        <%= form.text_field :first_name, placeholder: "Nombre", class: "form-control" %>
                      </div>
                    </div>
                      
                    <div class="col-md-6">
                      <div class="form-group">
                        <%= form.text_field :last_name, placeholder: "Apellido", class: "form-control" %>
                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :restaurant_name, placeholder: "Nombre de restaurante", class: "form-control" %>
                      </div>
                    </div>
                    
                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :email, placeholder: "Correo electronico", class: "form-control" %>
                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :phone_number, placeholder: "Número de teléfono", class: "form-control" %>
                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :address, placeholder: "Dirección", class: "form-control" %>
                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :city, placeholder: "Ciudad", class: "form-control" %>
                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :country, placeholder: "País", class: "form-control" %>
                      </div>
                    </div>

                    <div class="col-md-12">
                      <div class="form-group" style="margin-top: 10px;">
                        <%= form.text_field :postal_code, placeholder: "Còdigo postal", class: "form-control" %>
                      </div>
                    </div>

                    <div class="actions text-center">
                      <%= form.submit "Enviar", class: "btn btn-primary restaurant-demo-btn btn-lg" %>
                    </div>
                  </div>
                <% end %>
            </div>
    </div>
  </div>
</div>



<%= render 'layouts/footer' %>